/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 355427cb2cbd3d9b8086be28d194c03d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "SEOArticleAgent";
	}
	interface Env {
		ARTICLES_KV: KVNamespace;
		IMAGES_R2: R2Bucket;
		SKILLS_DB: D1Database;
		SKILL_FETCH_QUEUE: Queue;
		AI: Ai;
		ASSETS: Fetcher;
		/**
		 * Service binding to the petinsurance Worker. Post-publish URL probes use
		 * worker-to-worker fetch so verification bypasses public DNS/edge/WAF.
		 */
		PETINSURANCE?: Fetcher;
		AMAZON_AFFILIATE_TAG: "catsluvus03-20";
		DOMAIN: "catsluvus.com";
		CLOUDFLARE_ZONE_ID: "646da2c86dbbe1dff196c155381b0704";
		CLOUDFLARE_ACCOUNT_ID: "bc8e15f958dc350e00c0e39d80ca6941";
		SEOArticleAgent: DurableObjectNamespace<import("./src/server").SEOArticleAgent>;
		/**
		 * AI Search instance — web-crawler indexed against catsluvus.com.
		 * Binding type: single instance (`ai_search` in wrangler.jsonc).
		 * Used by fetchSemanticInternalLinks() to surface topically relevant
		 * articles for internal linking via hybrid semantic+keyword search.
		 * Falls back silently to the SQLite recency query when not available.
		 */
		AI_SEARCH?: AiSearchInstance;
		// Secrets (from Doppler → wrangler secret put)
		/**
		 * Doppler service token (dp.st.…) for direct Doppler REST API reads —
		 * used by the OpenRouter-key rotation self-heal.
		 */
		DOPPLER_TOKEN?: string;
		/**
		 * Google Cloud service-account JSON key (the full
		 * `{ "client_email", "private_key", ... }` document). Powers the
		 * direct Google Sheets connector (src/pipeline/google-sheets-direct.ts)
		 * ("Sheet mirror"). The target spreadsheet must be shared with the
		 * service account's client_email.
		 */
		GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON?: string;
		/**
		 * Amazon Creators API OAuth2 client_id — the registered
		 * Application's ID. Required for Tier-1 product fetch.
		 * NOT the same as the legacy `AMAZON_CREDENTIAL_ID`; using
		 * the wrong one causes Cognito to issue a bearer token that
		 * `searchItems` then rejects as `InvalidToken`.
		 */
		AMAZON_APP_ID?: string;
		/** Legacy fallback for AMAZON_APP_ID — pre-Creators-API name. */
		AMAZON_CREDENTIAL_ID?: string;
		AMAZON_API_SECRET?: string;
		/**
		 * Independent secondary Creators API credential pair. When the
		 * primary `AMAZON_APP_ID`/`AMAZON_API_SECRET` returns 401
		 * `InvalidToken`, Tier 1 retries with this pair before falling
		 * through to PA API v5 / Apify. Has its own circuit breaker so a
		 * primary 401 doesn't poison the fallback attempt.
		 */
		AMAZON_APP_ID_FALLBACK?: string;
		AMAZON_API_SECRET_FALLBACK?: string;
		/**
		 * Amazon Product Advertising API v5 credentials (AWS SigV4).
		 * Used by Tier 2 of the product-data chain in `fetchViaPaApi()`.
		 * Independent of the Creators API — works when that returns
		 * InvalidToken.
		 */
		AMAZON_ACCESS_KEY?: string;
		AMAZON_SECRET_KEY?: string;
		/**
		 * Independent secondary PA API v5 credential pair. When the primary
		 * pair returns 0 products or a SigV4 error, Tier 2 retries with
		 * this pair before falling through to Apify (Tier 3). Useful when
		 * the primary access key gets throttled, deauthorized, or
		 * Associates-account-suspended.
		 */
		AMAZON_ACCESS_KEY_FALLBACK?: string;
		AMAZON_SECRET_KEY_FALLBACK?: string;
		APIFY_TOKEN?: string;
		/**
		 * BrightData Web Unlocker credentials. When set, the Amazon
		 * product-page price scrape in `hydratePricesFromAmazonPages()`
		 * routes through BrightData's residential-IP proxy instead of
		 * fetching directly from Worker egress (which Amazon bot-blocks).
		 * Zone defaults to "web_unlocker1" when not set.
		 */
		BRIGHTDATA_API_KEY?: string;
		BRIGHTDATA_WEB_UNLOCKER_ZONE?: string;
		SERPER_API_KEY?: string;
		/**
		 * Google Custom Search JSON API key.
		 * Used by `analyzeSERP()` as the primary SERP source (100 free queries/day).
		 * Falls back to DuckDuckGo HTML scrape when not set.
		 */
		GOOGLE_API_KEY?: string;
		/**
		 * Google Programmable Search Engine ID (cx parameter).
		 * Required alongside GOOGLE_API_KEY for Custom Search API calls.
		 */
		GOOGLE_CSE_ID?: string;
		/**
		 * Brave Search API key (free tier: 2k queries/mo).
		 * When set, `analyzeSERP()` inserts Brave between Serper and
		 * Google CSE — Brave is the only keyless-to-cheap source that
		 * returns both organic results AND PAA-style FAQ entries.
		 */
		BRAVE_API_KEY?: string;
		/**
		 * Exa (Metaphor) Neural Search API key (free tier: 1k/mo).
		 * Semantic SERP fallback used by `analyzeSERP()` after SearXNG.
		 */
		EXA_API_KEY?: string;
		/**
		 * Etsy Open API v3 key — alternate retailer for the Amazon
		 * product chain in `writer.ts` when every Amazon tier fails.
		 */
		ETSY_API_KEY?: string;
		/**
		 * eBay Browse API key — alternate retailer sibling to
		 * ETSY_API_KEY in the Amazon fallback chain.
		 */
		EBAY_API_KEY?: string;
		/**
		 * Comma-separated list of SearXNG instance base URLs (e.g.
		 * "https://searx.be,https://priv.au").  `analyzeSERP()`
		 * round-robins across healthy instances.  Optional — tier is
		 * skipped when unset.
		 */
		SEARXNG_BASE_URLS?: string;
		CLOUDFLARE_API_TOKEN_SECRET?: string;
		INDEXNOW_KEY?: string;
		GITHUB_TOKEN_SECRET?: string;
		/**
		 * `owner/repo` for HTML article backup PRs (default
		 * `techfundoffice/catsluvus-cloudflare-kv-backup`).
		 */
		GITHUB_ARTICLE_BACKUP_REPOSITORY?: string;
		/**
		 * Override the deployed Worker base URL used in escalation issue
		 * runbooks and admin curl examples.  Defaults to the production
		 * Worker URL when not set.  Useful for staging/fork deployments.
		 * Set via: npx wrangler secret put WORKER_BASE_URL
		 */
		WORKER_BASE_URL?: string;
		/**
		 * GitHub repo owner for escalation issue creation.  Defaults to
		 * "techfundoffice".  Override for forks or staging environments.
		 * Set via: npx wrangler secret put REPO_OWNER
		 */
		REPO_OWNER?: string;
		/**
		 * GitHub repo name for escalation issue creation.  Defaults to
		 * "cats-seo-aiagent-cloudflare".  Override for forks or staging
		 * environments.  Set via: npx wrangler secret put REPO_NAME
		 */
		REPO_NAME?: string;
		/**
		 * HTTP Basic Auth password for the dashboard.
		 * Username is always "admin". Set via Doppler → `wrangler secret put DASHBOARD_PASSWORD`.
		 * When not set, the dashboard is publicly accessible (dev mode).
		 */
		DASHBOARD_PASSWORD?: string;
		/**
		 * OpenRouter API key. When set, Kimi K2.5 calls route through
		 * OpenRouter (~33% cheaper than Workers AI K2.5). Falls back to
		 * Workers AI automatically on HTTP error or empty response. Leave
		 * unset to stay on Workers AI only. Set via Doppler →
		 * `wrangler secret put OPENROUTER_API_KEY`.
		 */
		OPENROUTER_API_KEY?: string;
		/**
		 * Bearer token for the `/api/admin/*` debug/control surface.
		 * Consumed by `.github/workflows/claude.yml` so Claude Code in CI
		 * can read logs, inspect KV, and trigger keyword retries without
		 * shipping Cloudflare API credentials. Same value must exist as a
		 * GitHub Actions repo secret with the identical name. Set via
		 * `wrangler secret put ADMIN_API_TOKEN`.
		 */
		ADMIN_API_TOKEN?: string;
		/**
		 * Admin token for skill-catalog mutating endpoints
		 * (`/api/skills/seed-local`, `/api/skills/crawl/start`).
		 */
		SKILLS_ADMIN_TOKEN?: string;
		/**
		 * Endpoint of the Quadratic ingest shim that mirrors activity-log
		 * rows into the `seo.activity_log` Postgres table read by the
		 * self-hosted Quadratic file at https://quadratic.catsluvus.com.
		 * Best-effort tee alongside the Composio Google-Sheets writer; an
		 * outage here never blocks the pipeline.
		 * Default production URL:
		 *   https://ingest.quadratic.catsluvus.com/activity-log
		 */
		QUADRATIC_INGEST_URL?: string;
		/**
		 * Bearer token expected by the Quadratic ingest shim
		 * (`Authorization: Bearer <token>`). Set via Doppler →
		 * `wrangler secret put QUADRATIC_INGEST_TOKEN`.
		 */
		QUADRATIC_INGEST_TOKEN?: string;
		/**
		 * Full URL of the n8n Webhook node that receives a JSON POST after
		 * every successful article publish (`finalizeArticle()` in
		 * `src/pipeline/writer.ts`). Each request carries an
		 * `X-N8N-Signature: sha256=<hex>` header computed over the body
		 * using `N8N_WEBHOOK_SECRET`. When unset, the outbound notifier
		 * is a silent no-op. Set via `wrangler secret put N8N_WEBHOOK_URL`.
		 */
		N8N_WEBHOOK_URL?: string;
		/**
		 * Shared HMAC secret used for both directions of the n8n bridge:
		 *   - Signing the outbound publish-success POST (HMAC-SHA256
		 *     hex, `X-N8N-Signature` header).
		 *   - Authenticating the inbound `POST /api/n8n/log` route, where
		 *     n8n must include `Authorization: Bearer <secret>`.
		 * Distinct from `ADMIN_API_TOKEN` — separate trust boundary so
		 * leaking one does not grant access to the other surface. Set via
		 * `wrangler secret put N8N_WEBHOOK_SECRET`.
		 */
		N8N_WEBHOOK_SECRET?: string;
		/**
		 * DataForSEO HTTP Basic Auth credentials. Login is the account
		 * email; password is the API password from
		 * app.dataforseo.com/api-access (NOT the dashboard login). When
		 * both are set, finalizeArticle() in `src/pipeline/writer.ts`
		 * fires `fetchOnPageScore()` (`src/pipeline/dataforseo.ts`) via
		 * ctx.waitUntil after publish — submits the article URL to the
		 * DataForSEO crawler, polls /v3/on_page/summary until done, and
		 * persists the resulting onpage_score to `articles.dataforseo_score`.
		 * Set via `wrangler secret put DATAFORSEO_LOGIN` and
		 * `wrangler secret put DATAFORSEO_PASSWORD`. When unset the
		 * post-publish audit is a silent no-op.
		 */
		DATAFORSEO_LOGIN?: string;
		DATAFORSEO_PASSWORD?: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AMAZON_AFFILIATE_TAG" | "DOMAIN" | "CLOUDFLARE_ZONE_ID" | "CLOUDFLARE_ACCOUNT_ID">> {}
}
