export const LOCATIONS = [
  { value: 'France', label: '🇫🇷 France' },
  { value: 'Belgium', label: '🇧🇪 Belgium' },
  { value: 'Switzerland', label: '🇨🇭 Switzerland' },
  { value: 'Canada', label: '🇨🇦 Canada' },
  { value: 'United States', label: '🇺🇸 United States' },
  { value: 'United Kingdom', label: '🇬🇧 United Kingdom' },
  { value: 'Germany', label: '🇩🇪 Germany' },
  { value: 'Spain', label: '🇪🇸 Spain' },
  { value: 'Italy', label: '🇮🇹 Italy' },
  { value: 'Netherlands', label: '🇳🇱 Netherlands' },
  { value: 'Portugal', label: '🇵🇹 Portugal' },
  { value: 'Poland', label: '🇵🇱 Poland' },
  { value: 'Australia', label: '🇦🇺 Australia' },
  { value: 'Brazil', label: '🇧🇷 Brazil' },
  { value: 'Mexico', label: '🇲🇽 Mexico' },
  { value: 'Japan', label: '🇯🇵 Japan' },
  { value: 'India', label: '🇮🇳 India' },
];

export const LANGUAGES = [
  { value: 'French', label: 'French' },
  { value: 'English', label: 'English' },
  { value: 'German', label: 'Deutsch' },
  { value: 'Spanish', label: 'Español' },
  { value: 'Italian', label: 'Italiano' },
  { value: 'Dutch', label: 'Nederlands' },
  { value: 'Portuguese', label: 'Portuguese' },
  { value: 'Polish', label: 'Polski' },
  { value: 'Japanese', label: '日本語' },
  { value: 'Russian', label: 'Русский' },
  { value: 'Arabic', label: 'العربية' },
  { value: 'Chinese Simplified', label: '中文 (简体)' },
];
